# Generated by Django 4.1.7 on 2023-03-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_director_alter_movie_description_alter_movie_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
