# Generated by Django 4.1.7 on 2023-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_genere_movie_gengere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gengere',
        ),
        migrations.AddField(
            model_name='movie',
            name='gengere',
            field=models.ManyToManyField(blank=True, null=True, to='films.genere'),
        ),
    ]
