# Generated by Django 4.1.7 on 2023-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_actor_director_slug_movie_avg_rating_movie_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='director',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
