# Generated by Django 4.1.7 on 2023-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_person_remove_movie_director_movie_actor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='frie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='potato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(default='T', max_length=2),
        ),
    ]
