# Generated by Django 4.1.7 on 2023-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_delete_actor_delete_director_remove_movie_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
